/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JocsParaules;

import Conexio.ConexioBD;
import Conexio.ErrorConexio;
import Conexio.Puntuacio;
import IniciarSessio.Login;
import Paraules.JocsParaules;
import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Albert
 */
public class EscriureLaParaulaJoc extends javax.swing.JFrame {

    /**
     * Creates new form EscriuLaParaulaJoc
     */
    public String[] ImatgesParaules = new String[15];

    public Set<Integer> numerosGenerados = new HashSet<>();

    Random r = new Random();

    public int numero = 0;

    public int RespostaCorrecta = 0;

    public int RespostaIncorrecta = 0;

    public EscriureLaParaulaJoc() {
        initComponents();

        AmagarComponents();

        contarParaulesImatges();

        MostrarImatges();

        //setIconImage(Login.IconImage());
    }

    private void AmagarComponents() {
        Resultats.setVisible(false);

        EncertsText.setVisible(false);

        FalladesText.setVisible(false);

        Encerts.setVisible(false);

        Fallades.setVisible(false);
    }

    public String[] contarParaulesImatges() {

        ImatgesParaules[0] = "avió.png";
        ImatgesParaules[1] = "castell.png";
        ImatgesParaules[2] = "dinosaure.png";
        ImatgesParaules[3] = "drac.png";
        ImatgesParaules[4] = "espasa.png";
        ImatgesParaules[5] = "esquirol.png";
        ImatgesParaules[6] = "flors.png";
        ImatgesParaules[7] = "lleó.png";
        ImatgesParaules[8] = "lluna.png";
        ImatgesParaules[9] = "nadó.png";
        ImatgesParaules[10] = "peix.png";
        ImatgesParaules[11] = "pluja.png";
        ImatgesParaules[12] = "rellotge.png";
        ImatgesParaules[13] = "vaixell.png";
        ImatgesParaules[14] = "xocolata.png";

        return ImatgesParaules;

    }

    public int imatge;

    public void MostrarImatges() {

        ParaulaFicada.setEnabled(true);

        jButton2.setEnabled(true);

        do {
            imatge = r.nextInt(15);
        } while (!numerosGenerados.add(imatge));

        ImatgeParaula.setIcon(setIcono("/Imatges/EscriuLaParaula/" + ImatgesParaules[imatge], ImatgeParaula));

        numero++;

    }

    public Icon setIcono(String url, JLabel label) {

        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = label.getWidth();

        int alto = label.getHeight();

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ParaulaFicada = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Resultats = new javax.swing.JLabel();
        Encerts = new javax.swing.JLabel();
        EncertsText = new javax.swing.JLabel();
        FalladesText = new javax.swing.JLabel();
        Fallades = new javax.swing.JLabel();
        Resposta = new javax.swing.JLabel();
        ImatgeParaula = new javax.swing.JLabel();
        Paraula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("apendreABC - Escriure La Paraula");
        setResizable(false);

        jButton1.setText("Sortir del Joc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Escriure La Paraula");

        jLabel2.setText("Escriu la paraula que correspon amb la imatge amb lletres minúscules:");

        ParaulaFicada.setBackground(new java.awt.Color(0, 0, 0));
        ParaulaFicada.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        ParaulaFicada.setForeground(new java.awt.Color(255, 255, 255));
        ParaulaFicada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParaulaFicadaActionPerformed(evt);
            }
        });
        ParaulaFicada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ParaulaFicadaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ParaulaFicadaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ParaulaFicadaKeyTyped(evt);
            }
        });

        jButton2.setText("Següent");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Resultats.setText("Resultats:");

        Encerts.setText("0");

        EncertsText.setText("Encerts:");

        FalladesText.setText("Fallades:");

        Fallades.setText("0");

        Resposta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RespostaKeyReleased(evt);
            }
        });

        ImatgeParaula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ImatgeParaulaKeyReleased(evt);
            }
        });

        Paraula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(ParaulaFicada, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EncertsText)
                                    .addComponent(FalladesText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Resultats))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Fallades, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Encerts, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Paraula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)))))
                .addComponent(ImatgeParaula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ImatgeParaula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jButton1)
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(Resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Paraula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Resultats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EncertsText)
                                    .addComponent(Encerts))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FalladesText)
                                    .addComponent(Fallades))
                                .addGap(27, 27, 27))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ParaulaFicada, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(154, 154, 154))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        ConexioBD con = new ConexioBD();

        Connection cn = con.Conexion();

        if (cn == null) {

            ErrorConexio newframe = new ErrorConexio();

            newframe.setVisible(true);

        } else {

            JocsParaules newframe = new JocsParaules();

            newframe.setVisible(true);

            this.dispose();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ParaulaFicadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParaulaFicadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ParaulaFicadaActionPerformed

    int VegadesEnter = 0;


    private void ParaulaFicadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ParaulaFicadaKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_ParaulaFicadaKeyPressed

    private void MostrarParaula() {

        ImatgeParaula.requestFocusInWindow();

        String paraula = ParaulaFicada.getText();

        System.out.println(ImatgesParaules[imatge]);

        int indexPunt = ImatgesParaules[imatge].lastIndexOf(".");

        String paraulaCorrecta = ImatgesParaules[imatge].substring(0, indexPunt);

        if (paraula.equals(paraulaCorrecta)) {

            Resposta.setText("Correcte!");
            RespostaCorrecta++;

        } else {
            Resposta.setText("Incorrecte!");
            RespostaIncorrecta++;

        }

        ParaulaFicada.setEnabled(false);

        Paraula.setText(paraulaCorrecta.toUpperCase());
    }


    private void ParaulaFicadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ParaulaFicadaKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            VegadesEnter++;

            if (VegadesEnter == 1) {

                MostrarParaula();

            }

            if (VegadesEnter == 2) {

                BotoSeguent();

                VegadesEnter = 0;

            }

        }
    }//GEN-LAST:event_ParaulaFicadaKeyReleased

    private void ParaulaFicadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ParaulaFicadaKeyTyped
        // TODO add your handling code here:
        int keyChar = evt.getKeyChar();

        if (keyChar == 'ñ' || keyChar == 'Ñ') {
            evt.consume();

        }

        if (!Character.isLetter(keyChar)) {

            evt.consume();

        }

        if (ParaulaFicada.getText().length() == 9) {
            evt.consume();

        }
    }//GEN-LAST:event_ParaulaFicadaKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        VegadesEnter++;

        if (VegadesEnter == 1) {

            MostrarParaula();
        }

        if (VegadesEnter == 2) {

            BotoSeguent();

            VegadesEnter = 0;
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void RespostaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RespostaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_RespostaKeyReleased

    private void ImatgeParaulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ImatgeParaulaKeyReleased
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            VegadesEnter++;

            if (VegadesEnter == 1) {

                MostrarParaula();

            }

            if (VegadesEnter == 2) {

                BotoSeguent();

                VegadesEnter = 0;

            }

        }

    }//GEN-LAST:event_ImatgeParaulaKeyReleased

    public void BotoSeguent() {

        ParaulaFicada.setEnabled(true);

        ParaulaFicada.requestFocusInWindow();

        Paraula.setText("");

        Resposta.setText("");

        ParaulaFicada.setText("");

        if (numero < 15) {

            MostrarImatges();

        } else {

            Resposta.setText("");
            jLabel2.setText("");
            ParaulaFicada.setText("Joc Acabat!");

            Resultats.setVisible(true);

            EncertsText.setVisible(true);

            FalladesText.setVisible(true);

            Encerts.setVisible(true);

            Fallades.setVisible(true);

            Encerts.setText("" + RespostaCorrecta);
            Fallades.setText("" + RespostaIncorrecta);

            jButton2.setEnabled(false);

            ParaulaFicada.setEnabled(false);

            ConexioBD con = new ConexioBD();

            Connection cn = con.Conexion();

            if (cn == null) {

                ErrorConexio newframe = new ErrorConexio();

                newframe.setVisible(true);

            } else {

                Puntuacio puntuacio = new Puntuacio();

                String TipusPuntuacio = "puntuacio_paraules";

                puntuacio.RegistrarPuntuacio(RespostaCorrecta, TipusPuntuacio);

                puntuacio.SumarPuntuacioTotal();

            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscriureLaParaulaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscriureLaParaulaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscriureLaParaulaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscriureLaParaulaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscriureLaParaulaJoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encerts;
    private javax.swing.JLabel EncertsText;
    private javax.swing.JLabel Fallades;
    private javax.swing.JLabel FalladesText;
    private javax.swing.JLabel ImatgeParaula;
    private javax.swing.JLabel Paraula;
    private javax.swing.JTextField ParaulaFicada;
    private javax.swing.JLabel Resposta;
    private javax.swing.JLabel Resultats;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
