/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JocsParaules;

import Conexio.ConexioBD;
import Conexio.ErrorConexio;
import Conexio.Puntuacio;
import IniciarSessio.Login;
import Paraules.JocsParaules;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;

/**
 *
 * @author Albert
 */
public class FaltaUnaLletraJoc extends javax.swing.JFrame {

    /**
     * Creates new form TrobarLletraJoc
     */
    ConexioBD con = new ConexioBD();

    Connection cn = con.Conexion();

    public String[] paraules = new String[30];

    Random r = new Random();

    public char lletraSubstituida;

    public int numero = 0;

    public Set<Integer> numerosGenerados = new HashSet<>();

    public int RespostaCorrecta = 0;
    public int RespostaIncorrecta = 0;

    public FaltaUnaLletraJoc() {
        initComponents();

        AmagarComponents();

        contarParaules();

        MostrarParaules();

        //setIconImage(Login.IconImage());

    }

    private void AmagarComponents() {
        Resultats.setVisible(false);

        EncertsText.setVisible(false);

        FalladesText.setVisible(false);

        Encerts.setVisible(false);

        Fallades.setVisible(false);
    }

    public String[] contarParaules() {

        paraules[0] = "GAT";
        paraules[1] = "TAULA";
        paraules[2] = "CASA";
        paraules[3] = "ARBRE";
        paraules[4] = "SOL";
        paraules[5] = "LLUNA";
        paraules[6] = "AVIÓ";
        paraules[7] = "RIU";
        paraules[8] = "LLIBRE";
        paraules[9] = "LLAPIS";
        paraules[10] = "ORDINADOR";
        paraules[11] = "TELÈFON";
        paraules[12] = "JARDÍ";
        paraules[13] = "GUITARRA";
        paraules[14] = "CAFÈ";
        paraules[15] = "PLATJA";
        paraules[16] = "MÚSICA";
        paraules[17] = "AMOR";
        paraules[18] = "CEL";
        paraules[19] = "TERRA";
        paraules[20] = "FLOR";
        paraules[21] = "PAPALLONA";
        paraules[22] = "XOCOLATA";
        paraules[23] = "GELAT";
        paraules[24] = "MUNTANYA";
        paraules[25] = "BRAÇ";
        paraules[26] = "MÀ";
        paraules[27] = "RATOLÍ";
        paraules[28] = "TREBALLAR";
        paraules[29] = "PROGRAMAR";

        return paraules;

    }

    public void MostrarParaules() {

        LletraFicada.setEnabled(true);

        jButton2.setEnabled(true);

        int paraula;
        do {
            paraula = r.nextInt(30);
        } while (!numerosGenerados.add(paraula));

        String paraulaSencera = paraules[paraula];

        int random2 = r.nextInt(paraulaSencera.length());

        lletraSubstituida = paraulaSencera.charAt(random2);

        String paraulaTallada = paraulaSencera.substring(0, random2) + "_" + paraulaSencera.substring(random2 + 1);

        ParaulaMostrada.setText(paraulaTallada);

        numero++;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ParaulaMostrada = new javax.swing.JLabel();
        LletraFicada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Resposta = new javax.swing.JLabel();
        Resultats = new javax.swing.JLabel();
        EncertsText = new javax.swing.JLabel();
        Encerts = new javax.swing.JLabel();
        FalladesText = new javax.swing.JLabel();
        Fallades = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("apendreABC - Falta Una Lletra");
        setResizable(false);

        jButton1.setText("Sortir del Joc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Falta Una Lletra");

        ParaulaMostrada.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        LletraFicada.setBackground(new java.awt.Color(0, 0, 0));
        LletraFicada.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        LletraFicada.setForeground(new java.awt.Color(255, 255, 255));
        LletraFicada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LletraFicadaActionPerformed(evt);
            }
        });
        LletraFicada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LletraFicadaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LletraFicadaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LletraFicadaKeyTyped(evt);
            }
        });

        jLabel2.setText("Escriu la lletra que falta a continuació:");

        jButton2.setText("Següent");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Resultats.setText("Resultats:");

        EncertsText.setText("Encerts:");

        Encerts.setText("0");

        FalladesText.setText("Fallades:");

        Fallades.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ParaulaMostrada, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LletraFicada, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addComponent(Resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(Resultats))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(EncertsText))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(FalladesText, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fallades, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Encerts, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ParaulaMostrada, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LletraFicada, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Resultats)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncertsText)
                    .addComponent(Encerts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FalladesText)
                    .addComponent(Fallades))
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        ConexioBD con = new ConexioBD();

        Connection cn = con.Conexion();

        if (cn == null) {

            ErrorConexio newframe = new ErrorConexio();

            newframe.setVisible(true);

        } else {

            JocsParaules newframe = new JocsParaules();

            newframe.setVisible(true);

            this.dispose();

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void LletraFicadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LletraFicadaKeyTyped
        // TODO add your handling code here:
        int keyChar = evt.getKeyChar();

        if (keyChar == 'ñ' || keyChar == 'Ñ') {
            evt.consume();

        }

        if (!Character.isLetter(keyChar)) {

            evt.consume();

        }

        if (LletraFicada.getText().length() >= 1) {
            evt.consume();

        }

    }//GEN-LAST:event_LletraFicadaKeyTyped

    private void LletraFicadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LletraFicadaKeyReleased
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            BotoSeguent();
        }

        String texto = LletraFicada.getText();

        if (texto.length() == 1) {

            String textoMayusculas = texto.toUpperCase();

            LletraFicada.setText(textoMayusculas);

        }
    }//GEN-LAST:event_LletraFicadaKeyReleased

    private void LletraFicadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LletraFicadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LletraFicadaActionPerformed

    public void BotoSeguent() {

        LletraFicada.requestFocusInWindow();

        String lletra = LletraFicada.getText();

        if (lletra.equals(Character.toString(lletraSubstituida))) {

            Resposta.setText("Correcte!");
            RespostaCorrecta++;

        } else {
            Resposta.setText("Incorrecte!");
            RespostaIncorrecta++;

        }

        LletraFicada.setText("");

        if (numero < 30) {

            MostrarParaules();

        } else {

            jLabel2.setText("");
            ParaulaMostrada.setText("Joc Acabat!");

            Resultats.setVisible(true);

            EncertsText.setVisible(true);

            FalladesText.setVisible(true);

            Encerts.setVisible(true);

            Fallades.setVisible(true);

            Encerts.setText("" + RespostaCorrecta);
            Fallades.setText("" + RespostaIncorrecta);

            jButton2.setEnabled(false);

            LletraFicada.setEnabled(false);

            ConexioBD con = new ConexioBD();

            Connection cn = con.Conexion();

            if (cn == null) {

                ErrorConexio newframe = new ErrorConexio();

                newframe.setVisible(true);

            } else {

                Puntuacio puntuacio = new Puntuacio();

                String TipusPuntuacio = "puntuacio_paraules";

                puntuacio.RegistrarPuntuacio(RespostaCorrecta, TipusPuntuacio);

                puntuacio.SumarPuntuacioTotal();

            }

        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        BotoSeguent();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void LletraFicadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LletraFicadaKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_LletraFicadaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaltaUnaLletraJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaltaUnaLletraJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaltaUnaLletraJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaltaUnaLletraJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaltaUnaLletraJoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encerts;
    private javax.swing.JLabel EncertsText;
    private javax.swing.JLabel Fallades;
    private javax.swing.JLabel FalladesText;
    private javax.swing.JTextField LletraFicada;
    private javax.swing.JLabel ParaulaMostrada;
    private javax.swing.JLabel Resposta;
    private javax.swing.JLabel Resultats;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
