/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JocsLletres;

import Conexio.ConexioBD;
import Conexio.ErrorConexio;
import Conexio.Puntuacio;
import IniciarSessio.Login;
import Lletres.JocsLletres;
import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Albert
 */
public class PrimeraLletraJoc extends javax.swing.JFrame {

    /**
     * Creates new form TrobaLaLletraJoc
     */
    public String[] ImatgesParaules = new String[20];

    public Set<Integer> numerosGenerados = new HashSet<>();

    Random r = new Random();

    public int numero = 0;

    public int RespostaCorrecta = 0;

    public int RespostaIncorrecta = 0;

    public PrimeraLletraJoc() {
        initComponents();

        AmagarComponents();

        contarParaulesImatges();

        MostrarImatges();

        //setIconImage(Login.IconImage());
    }

    private void AmagarComponents() {
        Resultats.setVisible(false);

        EncertsText.setVisible(false);

        FalladesText.setVisible(false);

        Encerts.setVisible(false);

        Fallades.setVisible(false);

        JocAcabat.setVisible(false);
    }

    public String[] contarParaulesImatges() {

        ImatgesParaules[0] = "anell.png";
        ImatgesParaules[1] = "bicicleta.png";
        ImatgesParaules[2] = "cotxe.png";
        ImatgesParaules[3] = "diners.png";
        ImatgesParaules[4] = "elefant.png";
        ImatgesParaules[5] = "finestres.png";
        ImatgesParaules[6] = "guardiola.png";
        ImatgesParaules[7] = "joguina.png";
        ImatgesParaules[8] = "llum.png";
        ImatgesParaules[9] = "martell.png";
        ImatgesParaules[10] = "núvol.png";
        ImatgesParaules[11] = "ocell.png";
        ImatgesParaules[12] = "porta.png";
        ImatgesParaules[13] = "quadre.png";
        ImatgesParaules[14] = "robot.png";
        ImatgesParaules[15] = "senyal.png";
        ImatgesParaules[16] = "taula.png";
        ImatgesParaules[17] = "ulleres.png";
        ImatgesParaules[18] = "ventilador.png";
        ImatgesParaules[19] = "xilòfon.png";

        return ImatgesParaules;

    }

    public int imatge;

    public void MostrarImatges() {

        LletraFicada.setEnabled(true);

        jButton2.setEnabled(true);

        do {
            imatge = r.nextInt(20);
        } while (!numerosGenerados.add(imatge));

        ImatgeParaula.setIcon(setIcono("/Imatges/LletraInicial/" + ImatgesParaules[imatge], ImatgeParaula));

        numero++;

    }

    public Icon setIcono(String url, JLabel label) {

        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = label.getWidth();

        int alto = label.getHeight();

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Resposta = new javax.swing.JLabel();
        LletraFicada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Resultats = new javax.swing.JLabel();
        Encerts = new javax.swing.JLabel();
        EncertsText = new javax.swing.JLabel();
        FalladesText = new javax.swing.JLabel();
        Fallades = new javax.swing.JLabel();
        ImatgeParaula = new javax.swing.JLabel();
        Paraula = new javax.swing.JLabel();
        JocAcabat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("apendreABC - Primera Lletra");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jButton1.setText("Sortir del Joc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LletraFicada.setBackground(new java.awt.Color(0, 0, 0));
        LletraFicada.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        LletraFicada.setForeground(new java.awt.Color(255, 255, 255));
        LletraFicada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LletraFicadaActionPerformed(evt);
            }
        });
        LletraFicada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LletraFicadaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LletraFicadaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LletraFicadaKeyTyped(evt);
            }
        });

        jLabel2.setText("Escriu la primera lletra que correspon amb la imatge:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Primera Lletra");

        jButton2.setText("Següent");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Resultats.setText("Resultats:");

        Encerts.setText("0");

        EncertsText.setText("Encerts:");

        FalladesText.setText("Fallades:");

        Fallades.setText("0");

        ImatgeParaula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ImatgeParaulaKeyReleased(evt);
            }
        });

        Paraula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JocAcabat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JocAcabat.setText("Joc Acabat!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EncertsText)
                            .addComponent(FalladesText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resultats))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fallades, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Encerts, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(172, 172, 172)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JocAcabat)
                                    .addComponent(Paraula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LletraFicada, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(ImatgeParaula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LletraFicada, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(Resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(Paraula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JocAcabat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(Resultats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EncertsText)
                                    .addComponent(Encerts))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FalladesText)
                                    .addComponent(Fallades))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(ImatgeParaula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void BotoSeguent() {

        LletraFicada.setEnabled(true);

        LletraFicada.requestFocusInWindow();

        Paraula.setText("");

        Resposta.setText("");

        LletraFicada.setText("");

        if (numero < 20) {

            MostrarImatges();

        } else {

            Resposta.setText("");
            jLabel2.setText("");
            JocAcabat.setVisible(true);

            Resultats.setVisible(true);

            EncertsText.setVisible(true);

            FalladesText.setVisible(true);

            Encerts.setVisible(true);

            Fallades.setVisible(true);

            Encerts.setText("" + RespostaCorrecta);
            Fallades.setText("" + RespostaIncorrecta);

            jButton2.setEnabled(false);

            LletraFicada.setEnabled(false);

            ConexioBD con = new ConexioBD();

            Connection cn = con.Conexion();

            if (cn == null) {
               

                ErrorConexio newframe = new ErrorConexio();

                newframe.setVisible(true);

            } else {

                Puntuacio puntuacio = new Puntuacio();

                String TipusPuntuacio = "puntuacio_lletres";

                puntuacio.RegistrarPuntuacio(RespostaCorrecta, TipusPuntuacio);

                puntuacio.SumarPuntuacioTotal();

            }

        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ConexioBD con = new ConexioBD();

        Connection cn = con.Conexion();

        if (cn == null) {

            ErrorConexio newframe = new ErrorConexio();

            newframe.setVisible(true);

        } else {
            JocsLletres newframe = new JocsLletres();

        newframe.setVisible(true);

        this.dispose();
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LletraFicadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LletraFicadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LletraFicadaActionPerformed

    int VegadesEnter = 0;

    private void LletraFicadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LletraFicadaKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_LletraFicadaKeyPressed

    private void MostrarParaula() {

        LletraFicada.requestFocusInWindow();

        String lletra = LletraFicada.getText();

        char LletraCorrecta = ImatgesParaules[imatge].toUpperCase().charAt(0);

        if (lletra.equals(Character.toString(LletraCorrecta))) {

            Resposta.setText("Correcte!");
            RespostaCorrecta++;

        } else {
            Resposta.setText("Incorrecte!");
            RespostaIncorrecta++;

        }

        int indexPunt = ImatgesParaules[imatge].lastIndexOf(".");

        Paraula.setText(ImatgesParaules[imatge].substring(0, indexPunt).toUpperCase());

    }
    private void LletraFicadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LletraFicadaKeyReleased
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            VegadesEnter++;

            if (VegadesEnter == 1) {

                MostrarParaula();

            }

            if (VegadesEnter == 2) {

                BotoSeguent();

                VegadesEnter = 0;
            }
        }

        String texto = LletraFicada.getText();

        if (texto.length() == 1) {

            String textoMayusculas = texto.toUpperCase();

            LletraFicada.setText(textoMayusculas);

        }
    }//GEN-LAST:event_LletraFicadaKeyReleased

    private void LletraFicadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LletraFicadaKeyTyped
        // TODO add your handling code here:
        int keyChar = evt.getKeyChar();

        if (keyChar == 'ñ' || keyChar == 'Ñ') {
            evt.consume();

        }

        if (!Character.isLetter(keyChar)) {

            evt.consume();

        }

        if (LletraFicada.getText().length() >= 1) {
            evt.consume();

        }
    }//GEN-LAST:event_LletraFicadaKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        VegadesEnter++;

        if (VegadesEnter == 1) {

            MostrarParaula();
        }

        if (VegadesEnter == 2) {

            BotoSeguent();

            VegadesEnter = 0;
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void ImatgeParaulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ImatgeParaulaKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_ImatgeParaulaKeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_formKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeraLletraJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeraLletraJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeraLletraJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeraLletraJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeraLletraJoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encerts;
    private javax.swing.JLabel EncertsText;
    private javax.swing.JLabel Fallades;
    private javax.swing.JLabel FalladesText;
    private javax.swing.JLabel ImatgeParaula;
    private javax.swing.JLabel JocAcabat;
    private javax.swing.JTextField LletraFicada;
    private javax.swing.JLabel Paraula;
    private javax.swing.JLabel Resposta;
    private javax.swing.JLabel Resultats;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
