package Fills;

import Conexio.ConexioBD;
import Conexio.ErrorConexio;
import Usuaris.GestionarUsuari;
import IniciarSessio.Login;
import SelecionarJoc.TriarModeAplicacio;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Albert
 */
public class SeleccionarFills extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarFills
     */
    ConexioBD con = new ConexioBD();

    Connection cn = con.Conexion();

    private int[] idFills = new int[3];

    private String[] nomFills = new String[3];

    public static int IdFill;

    public static String NomFill;

    public static int getIdFill() {
        return IdFill;
    }

    public static String getNomFill() {
        return NomFill;
    }

    public static void setNomFill(String NomFill) {
        SeleccionarFills.NomFill = NomFill;
    }

    public SeleccionarFills() {

        initComponents();
        CarregarUsuari();
        mirarFillsUsuari();

        //setIconImage(Login.IconImage());

        this.getContentPane().setBackground(new Color(255, 225, 0));
        
        ConexioBD.PrimeraPantalla = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFills = new javax.swing.JLabel();
        RegistrarFill = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        UsuariCorreu = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        SeleccionarTercerFill = new javax.swing.JButton();
        SeleccionarPrimerFill = new javax.swing.JButton();
        SeleccionarSegonFill = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("apendreABC - Seleccionar Fills");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Qui apendra?");

        jLabel2.setText("Selecciona el fill que vols que utilitzi l'aplicació:");

        textFills.setText("Si no en tens cap mira de registrar-ne un:");

        RegistrarFill.setText("Registrar Fill");
        RegistrarFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarFillActionPerformed(evt);
            }
        });

        jLabel4.setText("Usuari:");

        UsuariCorreu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jButton2.setText("Tancar Sessió");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        SeleccionarTercerFill.setText("Fill 3");
        SeleccionarTercerFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarTercerFillActionPerformed(evt);
            }
        });

        SeleccionarPrimerFill.setText("Fill 1");
        SeleccionarPrimerFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarPrimerFillActionPerformed(evt);
            }
        });

        SeleccionarSegonFill.setText("Fill 2");
        SeleccionarSegonFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarSegonFillActionPerformed(evt);
            }
        });

        jButton3.setText("Gestionar Usuari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(74, Short.MAX_VALUE)
                        .addComponent(SeleccionarPrimerFill, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(SeleccionarSegonFill, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(SeleccionarTercerFill, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFills)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegistrarFill)))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(UsuariCorreu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jLabel4))
                    .addComponent(UsuariCorreu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccionarTercerFill, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionarSegonFill, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionarPrimerFill, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFills)
                    .addComponent(RegistrarFill)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mirarFillsUsuari() {

        Statement stmt;

        try {
            stmt = (Statement) cn.createStatement();

            String sql = "SELECT `id`, `Nom` FROM `fills` WHERE fills.usuari_id = '" + Login.getIdUsuari() + "'";

            ResultSet rs = stmt.executeQuery(sql);

            int nombreRegistres = 0;

            while (rs.next()) {

                idFills[nombreRegistres] = rs.getInt("id");

                nomFills[nombreRegistres] = rs.getString("Nom");

                nombreRegistres++;
            }

            if (nombreRegistres == 0) {

                SeleccionarPrimerFill.setEnabled(false);

                SeleccionarSegonFill.setEnabled(false);
                SeleccionarTercerFill.setEnabled(false);

            }

            if (nombreRegistres == 1) {

                SeleccionarPrimerFill.setEnabled(true);

                SeleccionarSegonFill.setEnabled(false);
                SeleccionarTercerFill.setEnabled(false);

                SeleccionarPrimerFill.setText(nomFills[0]);

            }

            if (nombreRegistres == 2) {

                SeleccionarPrimerFill.setEnabled(true);

                SeleccionarSegonFill.setEnabled(true);
                SeleccionarTercerFill.setEnabled(false);

                SeleccionarPrimerFill.setText(nomFills[0]);
                SeleccionarSegonFill.setText(nomFills[1]);

            }

            if (nombreRegistres == 3) {

                SeleccionarPrimerFill.setEnabled(true);

                SeleccionarSegonFill.setEnabled(true);
                SeleccionarTercerFill.setEnabled(true);

                SeleccionarPrimerFill.setText(nomFills[0]);
                SeleccionarSegonFill.setText(nomFills[1]);
                SeleccionarTercerFill.setText(nomFills[2]);

                RegistrarFill.setEnabled(false);

                textFills.setText("Ja has registrat un màxim de 3 fills!");

            }

            rs.close();
            stmt.close();

        } catch (SQLException ex) {
            Logger.getLogger(SeleccionarFills.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        ConexioBD con = new ConexioBD();

        Connection cn = con.Conexion();

        if (cn == null) {
            ErrorConexio newframe = new ErrorConexio();

            newframe.setVisible(true);

        } else {

            GestionarUsuari newframe = new GestionarUsuari();

            newframe.setVisible(true);

            this.dispose();
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void RegistrarFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarFillActionPerformed
        // TODO add your handling code here:

        ConexioBD con = new ConexioBD();

        Connection cn = con.Conexion();

        if (cn == null) {

            ErrorConexio newframe = new ErrorConexio();

            newframe.setVisible(true);

        } else {

            RegistrarFills newframe = new RegistrarFills();

            newframe.setVisible(true);

            this.dispose();

        }


    }//GEN-LAST:event_RegistrarFillActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            cn.close();

            Login newframe = new Login();

            newframe.setVisible(true);

            this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(SeleccionarFills.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void CrearPuntuacioFill() {

        Statement stmt;

        try {
            stmt = (Statement) cn.createStatement();

            String sql = "SELECT `fill_id` FROM `puntuacio` WHERE fill_id = '" + IdFill + "'";

            ResultSet rs = stmt.executeQuery(sql);

            if (!rs.next()) {

                stmt = (Statement) cn.createStatement();

                String sql2 = "INSERT INTO `puntuacio`(`fill_id`, `puntuacio_lletres`, `puntuacio_numeros`, `puntuacio_paraules`, `puntuacio_total`) VALUES ('" + IdFill + "','" + 0 + "','" + 0 + "','" + 0 + "'," + 0 + ")";
                stmt.executeUpdate(sql2);

                System.out.println("Puntuacio creada amb exit!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(SeleccionarFills.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    private void SeleccionarPrimerFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarPrimerFillActionPerformed
        // TODO add your handling code here:

        ConexioBD con = new ConexioBD();

        Connection cn = con.Conexion();

        if (cn == null) {

            ErrorConexio newframe = new ErrorConexio();

            newframe.setVisible(true);

        } else {

            IdFill = idFills[0];

            NomFill = nomFills[0];

            CrearPuntuacioFill();

            TriarModeAplicacio newframe = new TriarModeAplicacio();

            newframe.setVisible(true);

            this.dispose();

        }


    }//GEN-LAST:event_SeleccionarPrimerFillActionPerformed

    private void SeleccionarSegonFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarSegonFillActionPerformed
        // TODO add your handling code here:

        ConexioBD con = new ConexioBD();

        Connection cn = con.Conexion();

        if (cn == null) {

            ErrorConexio newframe = new ErrorConexio();

            newframe.setVisible(true);

        } else {

            IdFill = idFills[1];

            NomFill = nomFills[1];

            CrearPuntuacioFill();

            TriarModeAplicacio newframe = new TriarModeAplicacio();

            newframe.setVisible(true);

            this.dispose();
        }


    }//GEN-LAST:event_SeleccionarSegonFillActionPerformed

    private void SeleccionarTercerFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarTercerFillActionPerformed
        // TODO add your handling code here:

        ConexioBD con = new ConexioBD();

        Connection cn = con.Conexion();

        if (cn == null) {

            ErrorConexio newframe = new ErrorConexio();

            newframe.setVisible(true);

        } else {

            IdFill = idFills[2];

            NomFill = nomFills[2];

            CrearPuntuacioFill();

            TriarModeAplicacio newframe = new TriarModeAplicacio();

            newframe.setVisible(true);

            this.dispose();
        }


    }//GEN-LAST:event_SeleccionarTercerFillActionPerformed

    /**
     * @param args the command line arguments
     */
    public void CarregarUsuari() {

        Statement stmt;

        try {
            stmt = (Statement) cn.createStatement();

            String sql = "SELECT `Email` FROM `usuaris` WHERE usuaris.id = '" + Login.getIdUsuari() + "'";

            ResultSet rs = stmt.executeQuery(sql);

            if (rs.next()) {

                String email = rs.getString("Email");

                System.out.println("Usuari: " + email);

                UsuariCorreu.setText(email);

            } else {

                UsuariCorreu.setText("Error d'autenticació");

            }

            rs.close();
            stmt.close();

        } catch (SQLException ex) {
            Logger.getLogger(SeleccionarFills.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarFills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarFills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarFills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarFills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarFills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrarFill;
    private javax.swing.JButton SeleccionarPrimerFill;
    private javax.swing.JButton SeleccionarSegonFill;
    private javax.swing.JButton SeleccionarTercerFill;
    private javax.swing.JLabel UsuariCorreu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel textFills;
    // End of variables declaration//GEN-END:variables
}
