/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JocsNumeros;

import Conexio.ConexioBD;
import Conexio.ErrorConexio;
import Conexio.Puntuacio;
import IniciarSessio.Login;
import Numeros.JocsNumeros;
import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Albert
 */
public class NumerosAtleatorisJoc extends javax.swing.JFrame {

    /**
     * Creates new form NumerosAtleatorisJoc
     */
    public String[] ImatgesDaus = new String[6];

    public int[][] dau1 = new int[6][6];

    public int[][] dau2 = new int[6][6];

    HashSet<String> combinacionesUtilizadas = new HashSet<>();

    Random r = new Random();

    public int SumaDausReal;

    public int NumeroVegades;

    public int RespostaCorrecta;

    public int RespostaIncorrecta;

    public NumerosAtleatorisJoc() {
        initComponents();

        carregarArrays();

        carregarDaus();

        AmagarComponents();

        //setIconImage(Login.IconImage());

    }

    private void carregarArrays() {

        for (int i = 0; i < dau1.length; i++) {

            for (int j = 0; j < dau1[i].length; j++) {

                dau1[i][j] = i;

            }

        }

        for (int i = 0; i < dau2.length; i++) {

            for (int j = 0; j < dau2[i].length; j++) {

                dau2[i][j] = j;

            }

        }

        System.out.println("Dau 1:");

        for (int i = 0; i < dau1.length; i++) {

            for (int j = 0; j < dau1[i].length; j++) {

                System.out.print((dau1[i][j] + 1) + " ");

            }

            System.out.println();

        }

        System.out.println("Dau 2:");

        for (int i = 0; i < dau2.length; i++) {

            for (int j = 0; j < dau2[i].length; j++) {

                System.out.print((dau2[i][j] + 1) + " ");

            }

            System.out.println();

        }
    }

    private void AmagarComponents() {
        Resultats.setVisible(false);

        EncertsText.setVisible(false);

        FalladesText.setVisible(false);

        Encerts.setVisible(false);

        Fallades.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ImatgeDau1 = new javax.swing.JLabel();
        ImatgeDau2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NumeroFicat = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Resultats = new javax.swing.JLabel();
        EncertsText = new javax.swing.JLabel();
        Encerts = new javax.swing.JLabel();
        Fallades = new javax.swing.JLabel();
        FalladesText = new javax.swing.JLabel();
        Resposta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("apendreABC - Numeros Atleatoris");
        setResizable(false);

        jButton1.setText("Sortir del Joc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Numeros Atleatoris");

        jLabel2.setText("Escriu la suma dels daus:");

        NumeroFicat.setBackground(new java.awt.Color(0, 0, 0));
        NumeroFicat.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        NumeroFicat.setForeground(new java.awt.Color(255, 255, 255));
        NumeroFicat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroFicatActionPerformed(evt);
            }
        });
        NumeroFicat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NumeroFicatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NumeroFicatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumeroFicatKeyTyped(evt);
            }
        });

        jButton2.setText("Següent");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Resultats.setText("Resultats:");

        EncertsText.setText("Encerts:");

        Encerts.setText("0");

        Fallades.setText("0");

        FalladesText.setText("Fallades:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(ImatgeDau1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(ImatgeDau2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(Resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumeroFicat, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Resultats))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(EncertsText))
                                    .addComponent(FalladesText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Fallades, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Encerts, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImatgeDau1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImatgeDau2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumeroFicat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Resultats)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EncertsText)
                            .addComponent(Encerts))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FalladesText)
                            .addComponent(Fallades))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void carregarDaus() {

        for (int i = 0; i < ImatgesDaus.length; i++) {

            ImatgesDaus[i] = "dau" + (i + 1) + ".png";
        }

        boolean combinacioTrobada = false;

        while (combinacionesUtilizadas.size() < 36 && !combinacioTrobada) {

            int indiceDau1 = r.nextInt(6);
            int indiceDau2 = r.nextInt(6);

            String combinacion = indiceDau1 + "," + indiceDau2;

            if (!combinacionesUtilizadas.contains(combinacion)) {

                combinacionesUtilizadas.add(combinacion);

                int valorDau1 = dau1[indiceDau1][indiceDau2];
                int valorDau2 = dau2[indiceDau1][indiceDau2];

                System.out.println("Valor dau1: " + valorDau1);

                System.out.println("Valor dau2: " + valorDau2);

                SumaDausReal = (valorDau1 + 1) + (valorDau2 + 1);

                ImatgeDau1.setIcon(setIcono("/Imatges/Daus/" + ImatgesDaus[indiceDau1], ImatgeDau1));

                ImatgeDau2.setIcon(setIcono("/Imatges/Daus/" + ImatgesDaus[indiceDau2], ImatgeDau2));

                NumeroVegades++;

                combinacioTrobada = true;

            }

        }

    }

    public Icon setIcono(String url, JLabel label) {

        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = label.getWidth();

        int alto = label.getHeight();

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        ConexioBD con = new ConexioBD();

        Connection cn = con.Conexion();

        if (cn == null) {

            ErrorConexio newframe = new ErrorConexio();

            newframe.setVisible(true);

        } else {

            JocsNumeros newframe = new JocsNumeros();

            newframe.setVisible(true);

            this.dispose();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NumeroFicatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroFicatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroFicatActionPerformed

    private void NumeroFicatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroFicatKeyReleased
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            BotoSeguent();
        }


    }//GEN-LAST:event_NumeroFicatKeyReleased

    private void NumeroFicatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroFicatKeyTyped
        // TODO add your handling code here:
        int keyChar = evt.getKeyChar();

        if (!Character.isDigit(keyChar)) {

            evt.consume();

        }

        if (NumeroFicat.getText().length() == 2) {
            evt.consume();

        }
    }//GEN-LAST:event_NumeroFicatKeyTyped

    public void BotoSeguent() {

        NumeroFicat.requestFocusInWindow();

        String numero = NumeroFicat.getText();

        int num = 0;

        if (!numero.isEmpty()) {

            num = Integer.parseInt(numero);

        }

        if (num == SumaDausReal) {

            Resposta.setText("Correcte!");
            RespostaCorrecta++;

        } else {

            Resposta.setText("Incorrecte!");
            RespostaIncorrecta++;

        }

        NumeroFicat.setText("");

        if (NumeroVegades < 36) {

            carregarDaus();

        } else {

            Resultats.setVisible(true);

            EncertsText.setVisible(true);

            FalladesText.setVisible(true);

            Encerts.setVisible(true);

            Fallades.setVisible(true);

            Encerts.setText("" + RespostaCorrecta);
            Fallades.setText("" + RespostaIncorrecta);

            jButton2.setEnabled(false);

            NumeroFicat.setEnabled(false);

            ImatgeDau1.setEnabled(false);

            ImatgeDau2.setEnabled(false);

            ConexioBD con = new ConexioBD();

            Connection cn = con.Conexion();

            if (cn == null) {

                ErrorConexio newframe = new ErrorConexio();

                newframe.setVisible(true);

            } else {
                Puntuacio puntuacio = new Puntuacio();

                String TipusPuntuacio = "puntuacio_numeros";

                puntuacio.RegistrarPuntuacio(RespostaCorrecta, TipusPuntuacio);

                puntuacio.SumarPuntuacioTotal();
            }

        }

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        BotoSeguent();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void NumeroFicatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroFicatKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_NumeroFicatKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumerosAtleatorisJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumerosAtleatorisJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumerosAtleatorisJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumerosAtleatorisJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumerosAtleatorisJoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encerts;
    private javax.swing.JLabel EncertsText;
    private javax.swing.JLabel Fallades;
    private javax.swing.JLabel FalladesText;
    private javax.swing.JLabel ImatgeDau1;
    private javax.swing.JLabel ImatgeDau2;
    private javax.swing.JTextField NumeroFicat;
    private javax.swing.JLabel Resposta;
    private javax.swing.JLabel Resultats;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
