/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JocsNumeros;

import Conexio.ConexioBD;
import Conexio.ErrorConexio;
import Conexio.Puntuacio;
import IniciarSessio.Login;
import Numeros.JocsNumeros;
import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Albert
 */
public class SequenciaJoc extends javax.swing.JFrame {

    /**
     * Creates new form SecuenciaJoc
     */
    public String[] daus = new String[6];

    public int NumeroDau = 1;

    public int NumeroVegades;

    public int RespostaCorrecta;

    public int RespostaIncorrecta;

    public SequenciaJoc() {
        initComponents();
        carregarDaus();
        AmagarComponents();

        //setIconImage(Login.IconImage());
    }

    private void AmagarComponents() {
        Resultats.setVisible(false);

        EncertsText.setVisible(false);

        FalladesText.setVisible(false);

        Encerts.setVisible(false);

        Fallades.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        dau1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NumeroFicat = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        FalladesText = new javax.swing.JLabel();
        EncertsText = new javax.swing.JLabel();
        Resultats = new javax.swing.JLabel();
        Encerts = new javax.swing.JLabel();
        Fallades = new javax.swing.JLabel();
        dau2 = new javax.swing.JLabel();
        Resposta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("apendreABC - Seqüència");
        setResizable(false);

        jButton1.setText("Sortir del Joc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Seqüència de Numeros");

        jLabel2.setText("Escriu el numero dels daus:");

        NumeroFicat.setBackground(new java.awt.Color(0, 0, 0));
        NumeroFicat.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        NumeroFicat.setForeground(new java.awt.Color(255, 255, 255));
        NumeroFicat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroFicatActionPerformed(evt);
            }
        });
        NumeroFicat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NumeroFicatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NumeroFicatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumeroFicatKeyTyped(evt);
            }
        });

        jButton2.setText("Següent");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        FalladesText.setText("Fallades:");

        EncertsText.setText("Encerts:");

        Resultats.setText("Resultats:");

        Encerts.setText("0");

        Fallades.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(dau1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dau2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(Resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NumeroFicat, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(Resultats))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(EncertsText))
                                            .addComponent(FalladesText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Fallades, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Encerts, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel2)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dau1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dau2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumeroFicat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Resultats)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EncertsText)
                                    .addComponent(Encerts))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FalladesText)
                                    .addComponent(Fallades)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(Resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int NumeroDau1 = 0;
    int NumeroDau2 = 0;

    public void carregarDaus() {

        for (int i = 0; i < daus.length; i++) {

            daus[i] = "dau" + (i + 1) + ".png";
        }

        if (NumeroVegades == 0) {

            dau1.setIcon(setIcono("/Imatges/Daus/" + daus[NumeroDau1], dau1));

        } else if (NumeroVegades % 2 == 0) {

            dau1.setIcon(setIcono("/Imatges/Daus/" + daus[NumeroDau1], dau1));

            dau2.setIcon(setIcono("/Imatges/Daus/" + daus[NumeroDau2], dau2));

            NumeroDau1++;

        } else if (NumeroVegades % 2 == 1) {

            dau1.setIcon(setIcono("/Imatges/Daus/" + daus[NumeroDau1], dau1));

            dau2.setIcon(setIcono("/Imatges/Daus/" + daus[NumeroDau2], dau2));

            NumeroDau2++;

        }

        NumeroVegades++;

    }

    public Icon setIcono(String url, JLabel label) {

        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = label.getWidth();

        int alto = label.getHeight();

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        ConexioBD con = new ConexioBD();

        Connection cn = con.Conexion();

        if (cn == null) {

            ErrorConexio newframe = new ErrorConexio();

            newframe.setVisible(true);

        } else {

            JocsNumeros newframe = new JocsNumeros();

            newframe.setVisible(true);

            this.dispose();

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    public void BotoSeguent() {

        NumeroFicat.requestFocusInWindow();

        String numero = NumeroFicat.getText();

        int num = 0;

        if (!numero.isEmpty()) {

            num = Integer.parseInt(numero);

        }

        if (num == NumeroVegades) {

            Resposta.setText("Correcte!");
            RespostaCorrecta++;

        } else {

            Resposta.setText("Incorrecte!");
            RespostaIncorrecta++;

        }

        NumeroFicat.setText("");

        if (NumeroVegades != 12) {

            carregarDaus();

        } else {

            Resultats.setVisible(true);

            EncertsText.setVisible(true);

            FalladesText.setVisible(true);

            Encerts.setVisible(true);

            Fallades.setVisible(true);

            Encerts.setText("" + RespostaCorrecta);
            Fallades.setText("" + RespostaIncorrecta);

            jButton2.setEnabled(false);

            NumeroFicat.setEnabled(false);

            dau1.setEnabled(false);

            dau2.setEnabled(false);

            ConexioBD con = new ConexioBD();

            Connection cn = con.Conexion();

            if (cn == null) {

                ErrorConexio newframe = new ErrorConexio();

                newframe.setVisible(true);

            } else {
                Puntuacio puntuacio = new Puntuacio();

                String TipusPuntuacio = "puntuacio_numeros";

                puntuacio.RegistrarPuntuacio(RespostaCorrecta, TipusPuntuacio);

                puntuacio.SumarPuntuacioTotal();
            }
        }

    }
    private void NumeroFicatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroFicatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroFicatActionPerformed

    private void NumeroFicatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroFicatKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_NumeroFicatKeyPressed

    private void NumeroFicatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroFicatKeyReleased
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            BotoSeguent();
        }
    }//GEN-LAST:event_NumeroFicatKeyReleased

    private void NumeroFicatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroFicatKeyTyped
        // TODO add your handling code here:
        int keyChar = evt.getKeyChar();

        if (!Character.isDigit(keyChar)) {

            evt.consume();

        }

        if (NumeroFicat.getText().length() == 2) {
            evt.consume();

        }
    }//GEN-LAST:event_NumeroFicatKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        BotoSeguent();


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SequenciaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SequenciaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SequenciaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SequenciaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SequenciaJoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encerts;
    private javax.swing.JLabel EncertsText;
    private javax.swing.JLabel Fallades;
    private javax.swing.JLabel FalladesText;
    private javax.swing.JTextField NumeroFicat;
    private javax.swing.JLabel Resposta;
    private javax.swing.JLabel Resultats;
    private javax.swing.JLabel dau1;
    private javax.swing.JLabel dau2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
